#!/usr/bin/env python
# encoding: utf-8
"""
local_settings.py

Enviroment related settings. Should be different on the production server.

Created by Kang Zhang on 2010-09-26.
Copyright (c) 2010 Shanghai Jiao Tong University. All rights reserved.
"""

# need be regenerated on production server, for security reasons :-)
# could be generated by COOKIE_KEY = os.urandom(64)
COOKIE_KEY = '\xe4\xc0z\xc0|\x0b*o\xe7<\xe4i?\xf3X\x04\xc6\xad\x92\x87\x9d\xc3|\xdcj\x9b\x80S\xf6\x11\xc7\xaef\xfa\x89\xa2\xe9\xe4\x87\xb9rm\x1bk\x8f\xdf\xf9\xff\xca\xb4M-\xfc))\xdd\xa8\xe2\x9e\xdc%\x1dy0'

# This is the language for your site
LANGUAGE_CODE = 'zh_CN'